config/routes.rb
Rails.application.routes.draw do
  root to: 'public/items#home'

  namespace :public do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords',
    }

    get 'recipes/ranking', to: 'recipes#ranking', as: 'recipes_ranking'
    resources :recipes

    post '/like/:recipe_id', to: 'likes#like', as: 'like'
    delete '/like/:recipe_id', to: 'likes#unlike', as: 'unlike'

    resources :items, only: [:index, :show]

    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'user_withdraw'
    resources :users, only: [:show, :edit, :update]

    get 'gifts/nowgift', to: 'gifts#nowgift', as: 'nowgift'
  end

  namespace :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/admins/sessions',
      passwords: 'client/admins/passwords',
    }

    get 'recipes/home', to: 'recipes#home', as: 'recipe_home'
    get 'recipes/top', to: 'recipes#top', as: 'recipe_top'
    resources :recipes, only: [:index, :show]

    resources :items

    resources :users, only: [:index, :show]

    get 'gifts/nowgift', to: 'gifts#nowgift', as: 'nowgift'
    resources :gifts, only: [:new, :create, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :likes, dependent: :destroy
  has_many :like_recipes, through: :likes, source: :recipe
  attachment :image

  validates :name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :email, presence: true, length: { minimum: 1, maximum: 40 }
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true, length: { maximum: 100 }

  enum is_deleted: { available: false, withdrawal: true }
  def active_for_authentication?
    super && (is_deleted == "available")
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admins_admin!

  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @recipes = Recipe.where(user_id: @user.id).page(params[:page])
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/admins/users/index.html.erb
<div class="headline">ユーザー</div>
  <div class="container">
	  <% @users.each do |user| %>
	    <div class="admins_user_flex">
	      <div class="admins_user_image"><%= attachment_image_tag user, :image, size:'200x150' %></div>
		  <div class="admins_user_name">ユーザー名：<%= user.name %></div>
		  <div class="admins_user_info">
	        <%= link_to "このユーザー情報を見る", admins_user_path(user) %>
		  </div>
		</div>
	  <% end %>
      <div class="page"><%= paginate @users %></div>
  </div>

app/views/admins/users/show.html.erb
<div class="headline">ユーザー詳細</div>
  <div class="user_show">
    <div class="user_show_image">
      <%= attachment_image_tag @user, :image, size:'200x200' %>
    </div>
    <div class="content">
      <table>
        <tr>
          <td class="user_title">名前</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td class="user_title">コメント</td>
          <td><%= @user.comment %></td>
        </tr>
		<tr>
          <td class="user_title">郵便番号</td>
		  <td><%= @user.postal_code %></td>
	　　 </tr>
		<tr>
		  <td class="user_title">住所</td>
		  <td><%= @user.address %></td>
		</tr>
		<tr>
		  <td class="user_title">電話番号</td>
		  <td><%= @user.phone_number %></td>
		</tr>
		<tr>
		  <td class="user_title">メールアドレス</td>
		  <td><%= @user.email %></td>
		</tr>
		<tr>
		  <td class="user_title">会員ステータス</td>
		  <td><%= @user.is_deleted_i18n %></td>
		</tr>
      </table>
    </div>
  </div>

  <div class="headline">このユーザーが投稿したアレンジレシピ</div>
  <div class="dot">
  <div class="container">
    <% @recipes.eager_load(:item).each do |recipe| %>
      <div class="recipe_box">
        <div class="user_recipe">
          <%= link_to admins_recipe_path(recipe) do %>
            <div><%= attachment_image_tag recipe, :image, size:'150x100' %></div>
            <div class="user_recipe_name"><%= recipe.name %></div>
          <% end %>
        </div>
        <div class="iine">
          <%= render 'public/likes/admin_like', recipe: recipe %>
        </div>
        <div class="relation_item">
          <p><<この商品をアレンジ</p>
          <%= link_to admins_item_path(recipe.item) do %>
            <div class="user_recipe_item"><%= recipe.item.name %></div>
            <div><%= attachment_image_tag recipe.item, :image, size:'70x35' %></div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="page"><%= paginate @recipes %></div>
  </div>
</div>