config/routes.rb
Rails.application.routes.draw do
  root to: 'public/items#home'

  namespace :public do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords',
    }

    get 'recipes/ranking', to: 'recipes#ranking', as: 'recipes_ranking'
    resources :recipes

    post '/like/:recipe_id', to: 'likes#like', as: 'like'
    delete '/like/:recipe_id', to: 'likes#unlike', as: 'unlike'

    resources :items, only: [:index, :show]

    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'user_withdraw'
    resources :users, only: [:show, :edit, :update]

    get 'gifts/nowgift', to: 'gifts#nowgift', as: 'nowgift'
  end

  namespace :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/admins/sessions',
      passwords: 'client/admins/passwords',
    }

    get 'recipes/home', to: 'recipes#home', as: 'recipe_home'
    get 'recipes/top', to: 'recipes#top', as: 'recipe_top'
    resources :recipes, only: [:index, :show]

    resources :items

    resources :users, only: [:index, :show]

    get 'gifts/nowgift', to: 'gifts#nowgift', as: 'nowgift'
    resources :gifts, only: [:new, :create, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attachment :image
  belongs_to :item
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients
  has_many :liking_users, through: :likes, source: :user

  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :time, presence: true
  validates :how_to_make, presence: true, length: { minimum: 1, maximum: 200 }
  validates :item_id, presence: true
  validates :user_id, presence: true

  enum difficulty_level: { easy: 0, medium: 1, hard: 2 }

  ransacker :likes_count do
    query = '(SELECT COUNT(likes.recipe_id) FROM likes where likes.recipe_id = recipes.id GROUP BY likes.recipe_id)'
    Arel.sql(query)
  end

  def self.monthly_ranking
    beginning_of_month = period[:start_month]
    end_of_month = period[:end_month]
    joins(:likes).merge(Like.group(:recipe_id).order('count(recipe_id) desc')).
      where(created_at: beginning_of_month..end_of_month)
  end

  def self.monthly_top
    beginning_of_month = period[:start_month]
    end_of_month = period[:end_month]
    joins(:likes).merge(Like.group(:recipe_id).order('count(recipe_id) desc')).
      where(created_at: beginning_of_month..end_of_month).first
  end

  def self.period
    year = Time.now.strftime('%Y').to_i
    start_months = [1, 4, 7, 10]
    end_months = [3, 6, 9, 12]
    beginning_of_month_list = start_months.map { |m| Time.new(year, m).beginning_of_month }
    end_of_month_list = end_months.map { |m| Time.new(year, m).end_of_month }
    periods = beginning_of_month_list.zip(end_of_month_list)
    start_month = 0
    end_month = 0
    periods.each do |period|
      if period[0] < DateTime.now && DateTime.now < period[1]
        start_month = period[0]
        end_month = period[1]
      end
    end
    { start_month: start_month, end_month: end_month }
  end

  def self.previous_monthly_top
    pre_beginning_of_month = previous_period[:previous_start_month]
    pre_end_of_month = previous_period[:previous_end_month]
    joins(:likes).merge(Like.group(:recipe_id).order('count(recipe_id) desc')).
      where(created_at: pre_beginning_of_month..pre_end_of_month).first
  end

  def self.previous_period
    year = Time.now.strftime('%Y').to_i
    previous_start_months = [1, 4, 7, 10]
    previous_end_months = [3, 6, 9, 12]
    pre_beginning_of_month_list = previous_start_months.map { |m| Time.new(year, m).beginning_of_month }
    pre_end_of_month_list = previous_end_months.map { |m| Time.new(year, m).end_of_month }
    previous_periods = pre_beginning_of_month_list.zip(pre_end_of_month_list)
    previous_start_month = 0
    previous_end_month = 0
    previous_periods.each do |period|
      if period[0] < DateTime.now.prev_month(3) && DateTime.now.prev_month(3) < period[1]
        previous_start_month = period[0]
        previous_end_month = period[1]
      end
    end
    { previous_start_month: previous_start_month, previous_end_month: previous_end_month }
  end
end

app/controllers/admins/recipes_controller.rb
class Admins::RecipesController < ApplicationController
  before_action :authenticate_admins_admin!

  def home
    @recipes = Recipe.all
    @today_recipe = 0
    @recipes.each do |recipe|
      if recipe[:created_at].to_s.match(/#{Date.today}.+/)
        @today_recipe += 1
      end
    end
    @monthly_ranking = Recipe.monthly_ranking.page(params[:page])
  end

  def index
    if params[:q].present?
      @search = Recipe.ransack(search_params)
      @recipes = @search.result.page(params[:page])
    else
      params[:q] = { sorts: 'id desc' }
      @search = Recipe.ransack
      @recipes = Recipe.page(params[:page])
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def top
    @recipe_ranks = Recipe.monthly_top
    @previous_top_ranks = Recipe.previous_monthly_top
  end

  def search_params
    params.require(:q).permit(:sorts, :name_cont)
  end
end

app/helpers/admins/recipes_helper.rb
module Admins::RecipesHelper
end

app/views/admins/recipes/home.html.erb
<div class="container">
  <div class="headline">本日投稿されたレシピ<%= @today_recipe %>件</div>
  <div class="today_recipe_content">
  <% @recipes.each do |recipe| %>
    <div class="today_tecipe_box">
      <% if(recipe[:created_at].to_s.match(/#{Date.today.to_s}.+/)) %>
        <%= link_to recipe.name, admins_recipe_path(recipe) %>
      <% end %>
    </div>
  <% end %>
</div>
</div>

<div class="headline">今シーズンのレシピランキング</div>
  <div class="admins_period">
    <span class="period_font"><%= "#{Recipe.period[:start_month].month}月〜#{Recipe.period[:end_month].month}月" %></span>
  </div>
  <div class="dot">
  <div class="container">
  <% @monthly_ranking.each.with_index(1) do |monthly_ranking, c| %>
    <div class="ranking_recipe_background">
      <% case c %>
      <% when 1 %>
        <div class="rank_1">第<%= c %>位</div>
      <% when 2 %>
        <div class="rank_2">第<%= c %>位</div>
      <% when 3 %>
        <div class="rank_3">第<%= c %>位</div>
      <% else %>
        <div class="rank">第<%= c %>位</div>
      <% end %>
      <div class="ranking_recipe_box">
        <div class="ranking_image">
          <%= link_to public_recipe_path(monthly_ranking) do %>
            <%= attachment_image_tag monthly_ranking, :image, size:'150x100' %>
              <div class="ranking_recipi_name"><%= monthly_ranking.name %></div>
          <% end %>
        </div>
        <div class="ranking_info">
          <p>所要時間：<%= monthly_ranking.time %>分</p>
          <p>難易度：<% monthly_ranking.difficulty_level %></p>
        </div>
	      <div class="ranking_iine"><%= render 'public/likes/admin_like', recipe: monthly_ranking %></div>
        <div class="create">投稿日時：<%= monthly_ranking.created_at.to_s(:datetime_jp) %></div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="page"><%= paginate @monthly_ranking %></div>
  </div>

app/views/admins/recipes/index.html.erb
<div class="headline">投稿されたレシピ</div>
<div class="index_recipe_content">
  <div class="dot">
  <div class="index_search_box">
    <%= search_form_for @search, url: admins_recipes_path do |f| %>
      <%= f.select( :sorts, { '並び替え': 'id desc', '投稿の古い順': 'updated_at asc', '投稿の新しい順': 'updated_at desc', 'いいね!の多い順': 'likes_count desc' } , { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()'} ) %><br>
      <p>レシピ名で検索：<%= f.search_field :name_cont, placeholder: '検索するテキストを入力...' %></p>
      <%= f.submit ("検索") , class: 'search-btn'%></dd>
    <% end %>
  </div>
    <div class="container">
    <% @recipes.eager_load(:user).each do |recipe| %>
      <div class="index_recipe_box">
        <div class="index_recipe_image">
          <%= link_to admins_recipe_path(recipe) do %>
            <%= attachment_image_tag recipe, :image, size:'150x100' %>
            <div class="index_recipe_name"><%= recipe.name %></div>
          <% end %>
        </div>
        <div class="index_recipe_info">
          <p>所要時間：<%= recipe.time %>分</p>
          <p>難易度：<%= recipe.difficulty_level %></p>
        </div>
        <div class="index_recipe_iine">
          <%= render 'public/likes/admin_like', recipe: recipe %>
        </div>
        <div class="index_relation_user">
          <p><<投稿者</p>
          <%= link_to admins_user_path(recipe.user) do %>
            <%= attachment_image_tag recipe.user, :image, size:'50x50' %>
            <div class="relation_user_name"><%= recipe.user.name %></div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="page"><%= paginate @recipes %></div>
    </div>
  </div>
</div>

app/views/admins/recipes/show.html.erb
<div class="dot">
	<%= render 'public/recipes/show_recipe', recipe: @recipe %>
	<div class="col-lg-8"></div>
	<div class="col-lg-4">
	  <%= render 'public/likes/admin_like', recipe: @recipe %>
	</div>
</div>

app/views/admins/recipes/top.html.erb
<div class="headline"><i class="fas fa-crown"></i>今シーズンの最人気レシピ<i class="fas fa-crown"></i></div>
<div class="admins_period">
  <span class="admins_period_font"><%= "#{Recipe.period[:start_month].month}月〜#{Recipe.period[:end_month].month}月" %></span>
</div>
<div class="now_top_recipe">
<div class="dot">
<div class="container">
  <% if @recipe_ranks.present? %>
  <div class="admins_recipi_name">レシピ名「<%= @recipe_ranks.name %>」</div>
  	  <div class="row">
	  	  <div class="show_recipe_image col-lg-4">
	        <%= attachment_image_tag @recipe_ranks, :image, size:'250x170' %>
	      </div>
	      <div class="col-lg-5">
	      	<table class="table">
				<tr>
					<td class="recipe_title">材料</td>
					<td>
						<% @recipe_ranks.ingredients.each do |ingredient| %>
						  <%= ingredient.name %></br>
						<% end %>
				    </td>
				</tr>
				<tr>
					<td class="recipe_title">調理時間</td>
					<td><%= @recipe_ranks.time %>分</td>
				</tr>
				<tr>
					<td class="recipe_title">作り方</td>
					<td><%= @recipe_ranks.how_to_make %></td>
				</tr>
				<tr>
					<td class="recipe_title">難易度</td>
					<td><%= @recipe_ranks.difficulty_level_i18n %></td>
				</tr>
				<tr>
					<td class="recipe_title">投稿日時</td>
					<td><%= @recipe_ranks.created_at.to_s(:datetime_jp) %></td>
				</tr>
				<tr>
					<td class="recipe_title">投稿者</td>
					<td><%= link_to @recipe_ranks.user.name, admins_user_path(@recipe_ranks.user) %></td>
				</tr>
			</table>
	      </div>
	      <div class="col-lg-3"></div>
	　</div>
	  <div class="row">
	  	<div class="admins_recipe_iine">
	      <%= render 'public/likes/admin_like', recipe: @recipe_ranks %>
	    </div>
	  </div>
  <% end %>
</div>
</div>
</div>
<div class="headline"><i class="fas fa-crown"></i>前シーズンの最人気レシピ<i class="fas fa-crown"></i></div>
<div class="admins_period">
  <span class="admins_period_font"><%= "#{Recipe.previous_period[:previous_start_month].month}月〜#{Recipe.previous_period[:previous_end_month].month}月" %></span>
</div>
<div class="dot">
<div class="container">
  <% if @previous_top_ranks.present? %>
  <div class="admins_recipi_name">レシピ名「<%= @previous_top_ranks.name %>」</div>
  	  <div class="row">
	  	  <div class="show_recipe_image col-lg-4">
	        <%= attachment_image_tag @previous_top_ranks, :image, size:'250x170' %>
	      </div>
	      <div class="col-lg-5">
	      	<table class="table">
				<tr>
					<td class="recipe_title">材料</td>
					<td>
						<% @previous_top_ranks.ingredients.each do |ingredient| %>
						  <%= ingredient.name %></br>
						<% end %>
				    </td>
				</tr>
				<tr>
					<td class="recipe_title">調理時間</td>
					<td><%= @previous_top_ranks.time %>分</td>
				</tr>
				<tr>
					<td class="recipe_title">作り方</td>
					<td><%= @previous_top_ranks.how_to_make %></td>
				</tr>
				<tr>
					<td class="recipe_title">難易度</td>
					<td><%= @previous_top_ranks.difficulty_level_i18n %></td>
				</tr>
				<tr>
					<td class="recipe_title">投稿日時</td>
					<td><%= @previous_top_ranks.created_at.to_s(:datetime_jp) %></td>
				</tr>
				<tr>
					<td class="recipe_title">投稿者</td>
					<td><%= link_to @previous_top_ranks.user.name, admins_user_path(@previous_top_ranks.user) %></td>
				</tr>
			</table>
	      </div>
	      <div class="col-lg-3"></div>
	　</div>
	  <div class="row">
	  	<div class="admins_recipe_iine">
	      <%= render 'public/likes/admin_like', recipe: @previous_top_ranks %>
	    </div>
	  </div>
  <% end %>
</div>
</div>