config/routes.rb
Rails.application.routes.draw do
  root to: 'public/items#home'

  namespace :public do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords',
    }

    get 'recipes/ranking', to: 'recipes#ranking', as: 'recipes_ranking'
    resources :recipes

    post '/like/:recipe_id', to: 'likes#like', as: 'like'
    delete '/like/:recipe_id', to: 'likes#unlike', as: 'unlike'

    resources :items, only: [:index, :show]

    get 'users/unsubscribe', to: 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/withdraw', to: 'users#withdraw', as: 'user_withdraw'
    resources :users, only: [:show, :edit, :update]

    get 'gifts/nowgift', to: 'gifts#nowgift', as: 'nowgift'
  end

  namespace :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/admins/sessions',
      passwords: 'client/admins/passwords',
    }

    get 'recipes/home', to: 'recipes#home', as: 'recipe_home'
    get 'recipes/top', to: 'recipes#top', as: 'recipe_top'
    resources :recipes, only: [:index, :show]

    resources :items

    resources :users, only: [:index, :show]

    get 'gifts/nowgift', to: 'gifts#nowgift', as: 'nowgift'
    resources :gifts, only: [:new, :create, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/29089709f6.js" crossorigin="anonymous"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top" style="background-color: #FFFFFF; height: 70px;">
      <div class="">
        <% if admins_admin_signed_in? %>
          <%= link_to admins_recipe_home_path do %>
            <%= image_tag '/logo.jpg', class:"logo", alt: "ロゴ", title: "ロゴ", width: "200" %>
          <% end %>
         　 <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "前／今シーズン最人気レシピ", admins_recipe_top_path %></li>
              <li><%= link_to "今シーズンの景品", admins_nowgift_path %></li>
              <li><%= link_to "レシピ", admins_recipes_path %></li>
              <li><%= link_to "商品", admins_items_path %></li>
              <li><%= link_to "会員", admins_users_path %></li>
              <li><%= link_to "ログアウト", destroy_admins_admin_session_path, method: :delete %></li>
            </ul>

        <% elsif public_user_signed_in? %>
          <%= link_to root_path do %>
            <%= image_tag '/logo.jpg', class:"logo", alt: "ロゴ", title: "ロゴ", width: "200" %>
          <% end %>
            <ul class="nav navbar-nav navbar-right">
              <li>ようこそ、<%= current_public_user.name %>さん！</li>
              <li><%= link_to "マイページ", public_user_path(current_public_user) %></li>
              <li><%= link_to "商品", public_items_path %></li>
              <li><%= link_to "レシピ", public_recipes_path %></li>
              <li><%= link_to "シーズンレシピランキング", public_recipes_ranking_path %></li>
              <li><%= link_to "今シーズンの景品", public_nowgift_path %></li>
              <li><%= link_to "ログアウト", destroy_public_user_session_path, method: :delete %></li>
            </ul>

        <% else %>
          <%= link_to root_path do %>
            <%= image_tag '/logo.jpg', class:"logo", alt: "ロゴ", title: "ロゴ", width: "200" %>
          <% end %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "商品", public_items_path %></li>
              <li><%= link_to "新規登録", new_public_user_registration_path %></li>
              <li><%= link_to "ログイン", public_user_session_path %></li>
              <li><%= link_to "管理者ログイン", admins_admin_session_path %></li>
            </ul>
        <% end %>
      </div>
    </header>

    <div class="main">
      <%= yield %>
    </div>
  </body>

  <footer>
    <div class="rights"><span>&copy;</span>2020 sunny milk株式会社 All Rights Reversed</div>
  </footer>
</html>